name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Update version number as needed
          release_name: Release v1.0.0
          body: |
            Changes in this release:
            - Added feature X
            - Fixed bug Y
          draft: false
          prerelease: false